"""add CalendarEvent and ConferenceRoom

Revision ID: cade42450e6e
Revises: 07b7a75e441b
Create Date: 2025-02-28 21:38:43.670011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "cade42450e6e"
down_revision: Union[str, None] = "07b7a75e441b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conferenceroom",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("manager_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["manager_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calendarevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "event_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("agenda", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"], ["conferenceroom.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calendareventparticipants",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["calendarevent.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendareventparticipants")
    op.drop_table("calendarevent")
    op.drop_table("conferenceroom")
    # ### end Alembic commands ###
